
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

def send_feedback_email(to_email, athlete_name, risk_level, recovery_time, forecast, cluster):
    sender_email = "your_email@example.com"
    sender_password = "your_password"  # Use environment variable or secure vault in production

    subject = "Your Athlete Injury Risk & Recovery Report - The Predictor"

    body = f"""Hello {athlete_name},

Here is your performance report generated by The Predictor:

- Injury Risk Level: {risk_level}
- Estimated Recovery Time: {recovery_time} days
- Injury Forecast: {forecast}
- Cluster Category: {cluster}

Stay fit and train smart!

Regards,
The Predictor Team
"""

    message = MIMEMultipart()
    message['From'] = sender_email
    message['To'] = to_email
    message['Subject'] = subject
    message.attach(MIMEText(body, 'plain'))

    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender_email, sender_password)
        server.send_message(message)
        server.quit()
        return True
    except Exception as e:
        print(f"Email sending error: {e}")
        return False
